//
//  CurrencyList.swift
//  Converter
//
//  Created by Umut Cörüt on 5.07.2022.
//

import Foundation

let currencyList = [
    Currency(name: "AED", flag: "🇦🇪"),
    Currency(name: "ALL", flag: "🇦🇱"),
    Currency(name: "AMD", flag: "🇦🇲"),
    Currency(name: "AUD", flag: "🇦🇺"),
    Currency(name: "AZN", flag: "🇦🇿"),
    Currency(name: "BAM", flag: "🇧🇦"),
    Currency(name: "BDT", flag: "🇧🇩"),
    Currency(name: "BHD", flag: "🇧🇭"),
    Currency(name: "BTC", flag: "฿  "),
    Currency(name: "CAD", flag: "🇨🇦"),
    Currency(name: "CHF", flag: "🇨🇭"),
    Currency(name: "CNY", flag: "🇨🇳"),
    Currency(name: "CZK", flag: "🇨🇿"),
    Currency(name: "DKK", flag: "🇩🇰"),
    Currency(name: "DZD", flag: "🇩🇿"),
    Currency(name: "EUR", flag: "🇪🇺"),
    Currency(name: "GBP", flag: "🇬🇧"),
    Currency(name: "GEL", flag: "🇬🇪"),
    Currency(name: "HKD", flag: "🇭🇰"),
    Currency(name: "IDR", flag: "🇮🇩"),
    Currency(name: "ILS", flag: "🇮🇱"),
    Currency(name: "INR", flag: "🇮🇳"),
    Currency(name: "IQD", flag: "🇮🇶"),
    Currency(name: "IRR", flag: "🇮🇷"),
    Currency(name: "JPY", flag: "🇯🇵"),
    Currency(name: "KRW", flag: "🇰🇷"),
    Currency(name: "KWD", flag: "🇰🇼"),
    Currency(name: "KZT", flag: "🇰🇿"),
    Currency(name: "MAD", flag: "🇲🇦"),
    Currency(name: "MYR", flag: "🇲🇾"),
    Currency(name: "NOK", flag: "🇳🇴"),
    Currency(name: "NZD", flag: "🇳🇿"),
    Currency(name: "PKR", flag: "🇵🇰"),
    Currency(name: "QAR", flag: "🇶🇦"),
    Currency(name: "RUB", flag: "🇷🇺"),
    Currency(name: "SAR", flag: "🇸🇦"),
    Currency(name: "SEK", flag: "🇸🇪"),
    Currency(name: "SGD", flag: "🇸🇬"),
    Currency(name: "TRY", flag: "🇹🇷"),
    Currency(name: "USD", flag: "🇺🇸"),
    Currency(name: "ZAR", flag: "🇿🇦"),
]
let ratesStandart = [
    "AED" : 1.00,
    "ALL" : 1.00,
    "AMD" : 1.00,
    "AUD" : 1.00,
    "AZN" : 1.00,
    "BAM" : 1.00,
    "BDT" : 1.00,
    "BHD" : 1.00,
    "BTC" : 1.00,
    "CAD" : 1.00,
    "CHF" : 1.00,
    "CNY" : 1.00,
    "CZK" : 1.00,
    "DKK" : 1.00,
    "DZD" : 1.00,
    "EUR" : 1.00,
    "GBP" : 1.00,
    "GEL" : 1.00,
    "HKD" : 1.00,
    "IDR" : 1.00,
    "ILS" : 1.00,
    "INR" : 1.00,
    "IQD" : 1.00,
    "IRR" : 1.00,
    "JPY" : 1.00,
    "KRW" : 1.00,
    "KWD" : 1.00,
    "KZT" : 1.00,
    "MAD" : 1.00,
    "MYR" : 1.00,
    "NOK" : 1.00,
    "NZD" : 1.00,
    "PKR" : 1.00,
    "QAR" : 1.00,
    "RUB" : 1.00,
    "SAR" : 1.00,
    "SEK" : 1.00,
    "SGD" : 1.00,
    "TRY" : 1.00,
    "USD" : 1.00,
    "ZAR" : 1.00]
